# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataloader.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataloader.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61taloader.proto\";\n\x17\x43reateDataloaderRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\r\x12\x0c\n\x04keys\x18\x02 \x03(\r\"]\n\x18\x43reateDataloaderResponse\x12\x15\n\x04resp\x18\x01 \x01(\x0e\x32\x07.Status\x12\x17\n\x0fshared_mem_file\x18\x02 \x01(\t\x12\x11\n\tloader_id\x18\x03 \x01(\r\" \n\x0bNextRequest\x12\x11\n\tloader_id\x18\x01 \x01(\r\"6\n\x0cNextResponse\x12\x15\n\x04resp\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\r\",\n\x17\x44\x65leteDataloaderRequest\x12\x11\n\tloader_id\x18\x03 \x01(\r\"1\n\x18\x44\x65leteDataloaderResponse\x12\x15\n\x04resp\x18\x03 \x01(\x0e\x32\x07.Status*\x1b\n\x06Status\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x46\x61lse\x10\x01\x32\xc3\x01\n\nDataLoader\x12G\n\x10\x43reateDataloader\x12\x18.CreateDataloaderRequest\x1a\x19.CreateDataloaderResponse\x12#\n\x04Next\x12\x0c.NextRequest\x1a\r.NextResponse\x12G\n\x10\x44\x65leteDataloader\x12\x18.DeleteDataloaderRequest\x1a\x19.DeleteDataloaderResponseb\x06proto3'
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='False', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=363,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
Ok = 0
globals()['False'] = 1



_CREATEDATALOADERREQUEST = _descriptor.Descriptor(
  name='CreateDataloaderRequest',
  full_name='CreateDataloaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='CreateDataloaderRequest.dataset_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='CreateDataloaderRequest.keys', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=79,
)


_CREATEDATALOADERRESPONSE = _descriptor.Descriptor(
  name='CreateDataloaderResponse',
  full_name='CreateDataloaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='CreateDataloaderResponse.resp', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shared_mem_file', full_name='CreateDataloaderResponse.shared_mem_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='CreateDataloaderResponse.loader_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=174,
)


_NEXTREQUEST = _descriptor.Descriptor(
  name='NextRequest',
  full_name='NextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='NextRequest.loader_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=208,
)


_NEXTRESPONSE = _descriptor.Descriptor(
  name='NextResponse',
  full_name='NextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='NextResponse.resp', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='NextResponse.address', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=264,
)


_DELETEDATALOADERREQUEST = _descriptor.Descriptor(
  name='DeleteDataloaderRequest',
  full_name='DeleteDataloaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='DeleteDataloaderRequest.loader_id', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=310,
)


_DELETEDATALOADERRESPONSE = _descriptor.Descriptor(
  name='DeleteDataloaderResponse',
  full_name='DeleteDataloaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='DeleteDataloaderResponse.resp', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=361,
)

_CREATEDATALOADERRESPONSE.fields_by_name['resp'].enum_type = _STATUS
_NEXTRESPONSE.fields_by_name['resp'].enum_type = _STATUS
_DELETEDATALOADERRESPONSE.fields_by_name['resp'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['CreateDataloaderRequest'] = _CREATEDATALOADERREQUEST
DESCRIPTOR.message_types_by_name['CreateDataloaderResponse'] = _CREATEDATALOADERRESPONSE
DESCRIPTOR.message_types_by_name['NextRequest'] = _NEXTREQUEST
DESCRIPTOR.message_types_by_name['NextResponse'] = _NEXTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteDataloaderRequest'] = _DELETEDATALOADERREQUEST
DESCRIPTOR.message_types_by_name['DeleteDataloaderResponse'] = _DELETEDATALOADERRESPONSE
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateDataloaderRequest = _reflection.GeneratedProtocolMessageType('CreateDataloaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATALOADERREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:CreateDataloaderRequest)
  })
_sym_db.RegisterMessage(CreateDataloaderRequest)

CreateDataloaderResponse = _reflection.GeneratedProtocolMessageType('CreateDataloaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATALOADERRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:CreateDataloaderResponse)
  })
_sym_db.RegisterMessage(CreateDataloaderResponse)

NextRequest = _reflection.GeneratedProtocolMessageType('NextRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEXTREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:NextRequest)
  })
_sym_db.RegisterMessage(NextRequest)

NextResponse = _reflection.GeneratedProtocolMessageType('NextResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEXTRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:NextResponse)
  })
_sym_db.RegisterMessage(NextResponse)

DeleteDataloaderRequest = _reflection.GeneratedProtocolMessageType('DeleteDataloaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATALOADERREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:DeleteDataloaderRequest)
  })
_sym_db.RegisterMessage(DeleteDataloaderRequest)

DeleteDataloaderResponse = _reflection.GeneratedProtocolMessageType('DeleteDataloaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATALOADERRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:DeleteDataloaderResponse)
  })
_sym_db.RegisterMessage(DeleteDataloaderResponse)



_DATALOADER = _descriptor.ServiceDescriptor(
  name='DataLoader',
  full_name='DataLoader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=393,
  serialized_end=588,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateDataloader',
    full_name='DataLoader.CreateDataloader',
    index=0,
    containing_service=None,
    input_type=_CREATEDATALOADERREQUEST,
    output_type=_CREATEDATALOADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Next',
    full_name='DataLoader.Next',
    index=1,
    containing_service=None,
    input_type=_NEXTREQUEST,
    output_type=_NEXTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteDataloader',
    full_name='DataLoader.DeleteDataloader',
    index=2,
    containing_service=None,
    input_type=_DELETEDATALOADERREQUEST,
    output_type=_DELETEDATALOADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATALOADER)

DESCRIPTOR.services_by_name['DataLoader'] = _DATALOADER

# @@protoc_insertion_point(module_scope)
