# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntask.proto\"2\n\x11\x43reateTaskRequest\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x0f\n\x07weights\x18\x03 \x03(\x05\"y\n\x12\x43reateTaskResponse\x12(\n\x05state\x18\x01 \x01(\x0e\x32\x19.CreateTaskResponse.State\x12\x0f\n\x07task_id\x18\x02 \x01(\x04\x12\x0c\n\x04path\x18\x03 \x01(\t\"\x1a\n\x05State\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x46\x61lse\x10\x01\"!\n\x0eGetDataRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\"\"\n\x0fGetDataRespones\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x03\x32g\n\x04Task\x12\x31\n\x06\x43reate\x12\x12.CreateTaskRequest\x1a\x13.CreateTaskResponse\x12,\n\x07GetData\x12\x0f.GetDataRequest\x1a\x10.GetDataResponesb\x06proto3'
)



_CREATETASKRESPONSE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='CreateTaskResponse.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='False', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=161,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_CREATETASKRESPONSE_STATE)


_CREATETASKREQUEST = _descriptor.Descriptor(
  name='CreateTaskRequest',
  full_name='CreateTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='CreateTaskRequest.keys', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='CreateTaskRequest.weights', index=1,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=64,
)


_CREATETASKRESPONSE = _descriptor.Descriptor(
  name='CreateTaskResponse',
  full_name='CreateTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='CreateTaskResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='CreateTaskResponse.task_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='CreateTaskResponse.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATETASKRESPONSE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=187,
)


_GETDATAREQUEST = _descriptor.Descriptor(
  name='GetDataRequest',
  full_name='GetDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='GetDataRequest.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=222,
)


_GETDATARESPONES = _descriptor.Descriptor(
  name='GetDataRespones',
  full_name='GetDataRespones',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='GetDataRespones.address', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=258,
)

_CREATETASKRESPONSE.fields_by_name['state'].enum_type = _CREATETASKRESPONSE_STATE
_CREATETASKRESPONSE_STATE.containing_type = _CREATETASKRESPONSE
DESCRIPTOR.message_types_by_name['CreateTaskRequest'] = _CREATETASKREQUEST
DESCRIPTOR.message_types_by_name['CreateTaskResponse'] = _CREATETASKRESPONSE
DESCRIPTOR.message_types_by_name['GetDataRequest'] = _GETDATAREQUEST
DESCRIPTOR.message_types_by_name['GetDataRespones'] = _GETDATARESPONES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTaskRequest = _reflection.GeneratedProtocolMessageType('CreateTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKREQUEST,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:CreateTaskRequest)
  })
_sym_db.RegisterMessage(CreateTaskRequest)

CreateTaskResponse = _reflection.GeneratedProtocolMessageType('CreateTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKRESPONSE,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:CreateTaskResponse)
  })
_sym_db.RegisterMessage(CreateTaskResponse)

GetDataRequest = _reflection.GeneratedProtocolMessageType('GetDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAREQUEST,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:GetDataRequest)
  })
_sym_db.RegisterMessage(GetDataRequest)

GetDataRespones = _reflection.GeneratedProtocolMessageType('GetDataRespones', (_message.Message,), {
  'DESCRIPTOR' : _GETDATARESPONES,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:GetDataRespones)
  })
_sym_db.RegisterMessage(GetDataRespones)



_TASK = _descriptor.ServiceDescriptor(
  name='Task',
  full_name='Task',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=260,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Task.Create',
    index=0,
    containing_service=None,
    input_type=_CREATETASKREQUEST,
    output_type=_CREATETASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='Task.GetData',
    index=1,
    containing_service=None,
    input_type=_GETDATAREQUEST,
    output_type=_GETDATARESPONES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASK)

DESCRIPTOR.services_by_name['Task'] = _TASK

# @@protoc_insertion_point(module_scope)
