# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distributed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='distributed.proto',
  package='distributed',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64istributed.proto\x12\x0b\x64istributed\x1a\x0c\x63ommon.proto\"/\n\x13RegisterHostRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x04\"\'\n\x14RegisterHostResponse\x12\x0f\n\x07host_id\x18\x01 \x01(\x04\"-\n\x11\x44\x65leteHostRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"%\n\x12\x44\x65leteHostResponse\x12\x0f\n\x07host_id\x18\x01 \x01(\x04\"2\n\x0cSampleResult\x12\x11\n\tloader_id\x18\x01 \x01(\x04\x12\x0f\n\x07indices\x18\x02 \x03(\r\"\x1e\n\x10QueryHostRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"!\n\x11QueryHostResponse\x12\x0c\n\x04port\x18\x01 \x01(\x04\"F\n\x14\x43reateSamplerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\":\n\x15\x43reateSamplerResponse\x12\x0e\n\x06length\x18\x01 \x01(\x04\x12\x11\n\tloader_id\x18\x02 \x01(\x04\"F\n\x14\x44\x65leteSamplerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\"\x17\n\x15\x44\x65leteSamplerResponse\"\x1b\n\rSampleRequest\x12\n\n\x02ip\x18\x03 \x01(\t\"8\n\x0eSampleResponse\x12&\n\x03res\x18\x01 \x03(\x0b\x32\x19.distributed.SampleResult2\xf3\x03\n\x0e\x44istributedSvc\x12V\n\rCreateSampler\x12!.distributed.CreateSamplerRequest\x1a\".distributed.CreateSamplerResponse\x12V\n\rDeleteSampler\x12!.distributed.DeleteSamplerRequest\x1a\".distributed.DeleteSamplerResponse\x12J\n\tQueryHost\x12\x1d.distributed.QueryHostRequest\x1a\x1e.distributed.QueryHostResponse\x12\x41\n\x06Sample\x12\x1a.distributed.SampleRequest\x1a\x1b.distributed.SampleResponse\x12S\n\x0cRegisterHost\x12 .distributed.RegisterHostRequest\x1a!.distributed.RegisterHostResponse\x12M\n\nDeleteHost\x12\x1e.distributed.DeleteHostRequest\x1a\x1f.distributed.DeleteHostResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_REGISTERHOSTREQUEST = _descriptor.Descriptor(
  name='RegisterHostRequest',
  full_name='distributed.RegisterHostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.RegisterHostRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='distributed.RegisterHostRequest.port', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=95,
)


_REGISTERHOSTRESPONSE = _descriptor.Descriptor(
  name='RegisterHostResponse',
  full_name='distributed.RegisterHostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_id', full_name='distributed.RegisterHostResponse.host_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=136,
)


_DELETEHOSTREQUEST = _descriptor.Descriptor(
  name='DeleteHostRequest',
  full_name='distributed.DeleteHostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.DeleteHostRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='distributed.DeleteHostRequest.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=183,
)


_DELETEHOSTRESPONSE = _descriptor.Descriptor(
  name='DeleteHostResponse',
  full_name='distributed.DeleteHostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_id', full_name='distributed.DeleteHostResponse.host_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=222,
)


_SAMPLERESULT = _descriptor.Descriptor(
  name='SampleResult',
  full_name='distributed.SampleResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='distributed.SampleResult.loader_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indices', full_name='distributed.SampleResult.indices', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=274,
)


_QUERYHOSTREQUEST = _descriptor.Descriptor(
  name='QueryHostRequest',
  full_name='distributed.QueryHostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.QueryHostRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=306,
)


_QUERYHOSTRESPONSE = _descriptor.Descriptor(
  name='QueryHostResponse',
  full_name='distributed.QueryHostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='distributed.QueryHostResponse.port', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=341,
)


_CREATESAMPLERREQUEST = _descriptor.Descriptor(
  name='CreateSamplerRequest',
  full_name='distributed.CreateSamplerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='distributed.CreateSamplerRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='distributed.CreateSamplerRequest.dataset_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.CreateSamplerRequest.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=413,
)


_CREATESAMPLERRESPONSE = _descriptor.Descriptor(
  name='CreateSamplerResponse',
  full_name='distributed.CreateSamplerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='distributed.CreateSamplerResponse.length', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='distributed.CreateSamplerResponse.loader_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=473,
)


_DELETESAMPLERREQUEST = _descriptor.Descriptor(
  name='DeleteSamplerRequest',
  full_name='distributed.DeleteSamplerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='distributed.DeleteSamplerRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='distributed.DeleteSamplerRequest.dataset_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.DeleteSamplerRequest.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=545,
)


_DELETESAMPLERRESPONSE = _descriptor.Descriptor(
  name='DeleteSamplerResponse',
  full_name='distributed.DeleteSamplerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=570,
)


_SAMPLEREQUEST = _descriptor.Descriptor(
  name='SampleRequest',
  full_name='distributed.SampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='distributed.SampleRequest.ip', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=599,
)


_SAMPLERESPONSE = _descriptor.Descriptor(
  name='SampleResponse',
  full_name='distributed.SampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='distributed.SampleResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=657,
)

_SAMPLERESPONSE.fields_by_name['res'].message_type = _SAMPLERESULT
DESCRIPTOR.message_types_by_name['RegisterHostRequest'] = _REGISTERHOSTREQUEST
DESCRIPTOR.message_types_by_name['RegisterHostResponse'] = _REGISTERHOSTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteHostRequest'] = _DELETEHOSTREQUEST
DESCRIPTOR.message_types_by_name['DeleteHostResponse'] = _DELETEHOSTRESPONSE
DESCRIPTOR.message_types_by_name['SampleResult'] = _SAMPLERESULT
DESCRIPTOR.message_types_by_name['QueryHostRequest'] = _QUERYHOSTREQUEST
DESCRIPTOR.message_types_by_name['QueryHostResponse'] = _QUERYHOSTRESPONSE
DESCRIPTOR.message_types_by_name['CreateSamplerRequest'] = _CREATESAMPLERREQUEST
DESCRIPTOR.message_types_by_name['CreateSamplerResponse'] = _CREATESAMPLERRESPONSE
DESCRIPTOR.message_types_by_name['DeleteSamplerRequest'] = _DELETESAMPLERREQUEST
DESCRIPTOR.message_types_by_name['DeleteSamplerResponse'] = _DELETESAMPLERRESPONSE
DESCRIPTOR.message_types_by_name['SampleRequest'] = _SAMPLEREQUEST
DESCRIPTOR.message_types_by_name['SampleResponse'] = _SAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterHostRequest = _reflection.GeneratedProtocolMessageType('RegisterHostRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERHOSTREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.RegisterHostRequest)
  })
_sym_db.RegisterMessage(RegisterHostRequest)

RegisterHostResponse = _reflection.GeneratedProtocolMessageType('RegisterHostResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERHOSTRESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.RegisterHostResponse)
  })
_sym_db.RegisterMessage(RegisterHostResponse)

DeleteHostRequest = _reflection.GeneratedProtocolMessageType('DeleteHostRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEHOSTREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.DeleteHostRequest)
  })
_sym_db.RegisterMessage(DeleteHostRequest)

DeleteHostResponse = _reflection.GeneratedProtocolMessageType('DeleteHostResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEHOSTRESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.DeleteHostResponse)
  })
_sym_db.RegisterMessage(DeleteHostResponse)

SampleResult = _reflection.GeneratedProtocolMessageType('SampleResult', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERESULT,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.SampleResult)
  })
_sym_db.RegisterMessage(SampleResult)

QueryHostRequest = _reflection.GeneratedProtocolMessageType('QueryHostRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYHOSTREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.QueryHostRequest)
  })
_sym_db.RegisterMessage(QueryHostRequest)

QueryHostResponse = _reflection.GeneratedProtocolMessageType('QueryHostResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYHOSTRESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.QueryHostResponse)
  })
_sym_db.RegisterMessage(QueryHostResponse)

CreateSamplerRequest = _reflection.GeneratedProtocolMessageType('CreateSamplerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESAMPLERREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.CreateSamplerRequest)
  })
_sym_db.RegisterMessage(CreateSamplerRequest)

CreateSamplerResponse = _reflection.GeneratedProtocolMessageType('CreateSamplerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESAMPLERRESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.CreateSamplerResponse)
  })
_sym_db.RegisterMessage(CreateSamplerResponse)

DeleteSamplerRequest = _reflection.GeneratedProtocolMessageType('DeleteSamplerRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESAMPLERREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.DeleteSamplerRequest)
  })
_sym_db.RegisterMessage(DeleteSamplerRequest)

DeleteSamplerResponse = _reflection.GeneratedProtocolMessageType('DeleteSamplerResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESAMPLERRESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.DeleteSamplerResponse)
  })
_sym_db.RegisterMessage(DeleteSamplerResponse)

SampleRequest = _reflection.GeneratedProtocolMessageType('SampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREQUEST,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.SampleRequest)
  })
_sym_db.RegisterMessage(SampleRequest)

SampleResponse = _reflection.GeneratedProtocolMessageType('SampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERESPONSE,
  '__module__' : 'distributed_pb2'
  # @@protoc_insertion_point(class_scope:distributed.SampleResponse)
  })
_sym_db.RegisterMessage(SampleResponse)



_DISTRIBUTEDSVC = _descriptor.ServiceDescriptor(
  name='DistributedSvc',
  full_name='distributed.DistributedSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=660,
  serialized_end=1159,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSampler',
    full_name='distributed.DistributedSvc.CreateSampler',
    index=0,
    containing_service=None,
    input_type=_CREATESAMPLERREQUEST,
    output_type=_CREATESAMPLERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSampler',
    full_name='distributed.DistributedSvc.DeleteSampler',
    index=1,
    containing_service=None,
    input_type=_DELETESAMPLERREQUEST,
    output_type=_DELETESAMPLERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryHost',
    full_name='distributed.DistributedSvc.QueryHost',
    index=2,
    containing_service=None,
    input_type=_QUERYHOSTREQUEST,
    output_type=_QUERYHOSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sample',
    full_name='distributed.DistributedSvc.Sample',
    index=3,
    containing_service=None,
    input_type=_SAMPLEREQUEST,
    output_type=_SAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterHost',
    full_name='distributed.DistributedSvc.RegisterHost',
    index=4,
    containing_service=None,
    input_type=_REGISTERHOSTREQUEST,
    output_type=_REGISTERHOSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteHost',
    full_name='distributed.DistributedSvc.DeleteHost',
    index=5,
    containing_service=None,
    input_type=_DELETEHOSTREQUEST,
    output_type=_DELETEHOSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISTRIBUTEDSVC)

DESCRIPTOR.services_by_name['DistributedSvc'] = _DISTRIBUTEDSVC

# @@protoc_insertion_point(module_scope)
